#let acronyms = (
  NLP: "Natural Language Processing",
  LLM: "Large Language Model",
  RIG: "Regional Implementation Group",
  CRISP-DM: "Cross Industry Standard Process for Data Mining",
  AI: "Artificial Intelligence",
  AE: "Account Executive",
  API: "Application Programming Interface",
  MXP: "Multi Experience Platform",
  CRM: "Customer Relationship Management",
  aCMS: "Augmented Content Management System",
  GenAI: "Generative Artificial Intelligence",
  PoC: "Proof of Concept",
  PLM: "Pre-trained Language Model",
  CoT: "Chain-of-Thought",
  ROUGE: "Recall-Oriented Understudy for Gisting Evaluation",
  ID: "Identifier",
  CSV: "Comma-separated values",
  JSON: "JavaScript Object Notation",
  TTFT: "Time-To-First-Token",
  pp: "Prozentpunkt",
  KI: "Künstlicher Intelligenz",
  KPI: "Key Performance Indicator"
)